### ISSUE TITLE
Allow user to specify a URL as conversion input

### ISSUE THREAD

**Issue by RFoley** [idrsolutions/base-microservice-example#6]
**Describe the solution you'd like**

Title.

The user sends a POST request to the microservice containing a URL as opposed to a PDF file to convert.
The microservice then responds with a UUID before attempting to download the PDF from the specified URL and convert it.

We should add a new required parameter to the request called 'input' (or similar), which the requester can use to specify if they are uploading a file or specifying a URL. This could be easily extended to include other input types in the future that need to be handled differently. 

BaseServlet.doPost() should check this parameter, then call a separate method to handle each input type appropriately.

Example request:
```
POST http://[URL]/buildvu
{
    input="url"
    url="http://foo.bar/baz.pdf"
}
```

**Additional context**

- When giving a URL as input, the request doesn't need to be a multipart request
- May be worth adding a new state 'downloading' to the conversion status response to provide more info.
- May be worth automatically retrying to download the file if it fails the first time before failing the conversion
- Don't forget to add JavaDoc comments for any new methods you add (and update any existing ones you change where necessary)
- Don't forget to update the [API doc](https://github.com/idrsolutions/buildvu-microservice-example/blob/master/API.md) in the buildvu-microservice-example to include the new functionality
- I recommend doing the previous 2 points last.
- As usual, the clients will need updating to support this after it's implemented. We can create separate issues in the respective GitHub repos when we get to that.

**Comment by patricksheppard-IDR** [comment]
From what I can tell there is no point in setting a "downloading" state since, as the code stands, the file must be downloaded from the url before the initial convert request is responded to therefore stopping any calls to the poll() methods/functions in the clients while the file is being downloaded on the server.

**Comment by patricksheppard-IDR** [comment]
In terms of reporting failed downloads to the user: depending on the amount of retries he server makes, the clients initial request will timeout before the server is able to report back a failure.

**Comment by leonatherton** [comment]
@patricksheppard-IDR It sounds like the best solution may be to respond to the POST request without downloading the file first, what do you think?

**Comment by patricksheppard-IDR** [comment]
@leonatherton As the code stands it would be difficult to do this as the doPost() method expects file data before responding to the request. The only way I can see of getting around this would be to exit out of the method early and if the download fails set the Individual state to "Download failed" which would be picked up on the next poll from the client. This would also involve starting the conversion thread at a later point. This approach would involve a bit of code shuffling (which I'm happy to do if other people think it's worth it).
If you could think of a better way that would be great.

**Comment by patricksheppard-IDR** [comment]
After speaking to @leonatherton in person we have decided to split doPost() into two or more methods, which will be called at different times depending on whether the file is passed by POST or through a URL.

**Comment by patricksheppard-IDR** [comment]
After speaking with @leonatherton and @RFoley, it looks like going with a more extensible approach is going to be worth the extra effort. As Leon suggested, cloud convert is a good example to follow, [see here](https://cloudconvert.com/api/conversions#start). They allow the client to specify an input type, call the correct routine to deal with each individual input type.
Does anyone have thoughts or suggestions on this?

If this was to be decided in favor of, I would most likely cancel the current pull request that "fixes" this issue and start fresh (especially since I have committed a lot of javadoc from a separate issue into this branch).

**Comment by RFoley** [comment]
Updated issue to match new requirements

Let me know if not clear :)

**Comment by patricksheppard-IDR** [comment]
Yep that makes sense :) 

My proposition for solving this would be having an abstract class called ClientFile (or similar), which would have an abstract boolean get() method which would be overriden by a subclass designed to fetch a certain type of input. Then there would only need to be a switch statement in the doPost() method to determine which class to initialise.
The advantage of having a separate class for this would be that filename, filedata, and more could be stored in the class without having to worry about only being able to return one item from a method.
