### ISSUE TITLE
Use callbacks to notify the user that their file has finished converting

### ISSUE THREAD

**Issue by RFoley** [idrsolutions/base-microservice-example#7]
**Describe the solution you'd like**

Instead of the user repeatedly requesting the microservice for status updates, allow them to specify a callback URL / webhook the microservice can send a request to once conversion is complete.

**Additional context**
 - The user would need to handle accepting and dealing with the webhook themselves. API will be updated to describe the request format & content.

**Comment by daniel-warren** [comment]
Base changes have been done at https://github.com/idrsolutions/base-microservice-example/pull/12

**Comment by RFoley** [comment]
Closing as now complete
