### ISSUE TITLE
Support percent encoding in requests to allow use of foreign / special characters

### ISSUE THREAD

**Issue by RFoley** [idrsolutions/base-microservice-example#8]
**Is your feature request related to a problem? Please describe.**
At the moment, the microservice example doesn't handle percent encoding in requests.

For example, a file with the name "ブロッコリー.pdf" is encoded as "%E3%83%96%E3%83%AD%E3%83%83%E3%82%B3%E3%83%AA%E3%83%BC.pdf" in a HTTP request.

However, when the microservice example processes this file it doesn't decode it, then the regex filename filter renames it to "_E3_83_96_E3_83_AD_E3_83_83_E3_82_B3_E3_83_AA_E3_83_BC.pdf".
When the user downloads the output, it now has the wrong filename.

**Describe the solution you'd like**
In order to properly support special / foreign characters, the microservice should use percent encoding (as per [RFC-3986](https://www.ietf.org/rfc/rfc3986.txt)).

Filenames should be decoded, any Windows-prohibited chars removed, the file converted, then the filename header re-encoded before responding to the user.

**Additional context**
 - We should also update the filename regex filter to only strip out the few remaining characters allowed unencoded in URLs but prohibited in Windows filenames.

**Comment by leonatherton** [comment]
Fixed by https://github.com/idrsolutions/base-microservice-example/pull/44
